# Generated by Django 2.0.2 on 2018-02-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='order_id',
            new_name='operator_id',
        ),
    ]
