# Generated by Django 2.0.2 on 2018-02-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20180215_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_id', models.IntegerField(default=1000)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('coordinates', models.CharField(max_length=255)),
                ('assessed', models.BooleanField(default=False)),
                ('fined', models.BooleanField(default=False)),
                ('sender_id', models.IntegerField(default=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.Area')),
            ],
        ),
    ]
