# Generated by Django 2.0.2 on 2018-02-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='numbler_plate',
            field=models.CharField(default='GJ-05-7777', max_length=255),
        ),
    ]
