# Generated by Django 2.0.2 on 2018-02-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0005_auto_20180215_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='numbler_plate',
            new_name='number_plate',
        ),
    ]
