# Generated by Django 2.0.2 on 2018-04-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0007_auto_20180406_1519'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
    ]
